### ISSUE TITLE
Modules installed, nothing happens when running run.py

### ISSUE THREAD

**Issue by jdog3388** [open-deepnude/open-deepnude#10]
I installed all of the modules that it needed (cv2, torch, etc), and now executing `run.py` no longer errors, but nothing happens. It just exits after a brief moment; nothing is displayed, no errors. Any ideas?

**Comment by nchartouh221** [comment]
Any idea how to remove the watermarks??

**Comment by enextus** [comment]
Here you can get a full "cracked" version for testing.
https://t.me/thisDeepNude

**Comment by enextus** [comment]
> Any idea how to remove the watermarks??

Here you can get a full "cracked" version for testing.
https://t.me/thisDeepNude

**Comment by 2165998** [comment]
> > Any idea how to remove the watermarks??
> 
> Here you can get a full "cracked" version for testing.
> https://t.me/thisDeepNude

thanks ,brother!I find a new world~

**Comment by stacklikemind** [comment]
https://github.com/deepinstruction/deepnude_official
