### ISSUE TITLE
Does anybody runned this scripts?

### ISSUE THREAD

**Issue by s1q** [open-deepnude/open-deepnude#4]
I am tried to untie scripts from exe file by instruction from real cracker guy yet before this repo was created.
But I have a problem with PyTorch. 

```
...
from torch._C import *
ModuleNotFoundError: No module named 'torch._C'
```
This one made me stop my project for few days. I am tired to find the solution. Every google page for this error didn`t help me.

**Comment by s1q** [comment]
I am working in Linux. My PC config don`t working with CUDA (Ryzen 3 2200G with integrated graphics).

**Comment by comdet** [comment]
After rewriting run.py by rename all variables to human-readable and restructure, I'm able to run it on Windows with GTX1070 with python command.
The important file is 3 model .lib files,  libsqla, libsqlb, libsqlc, shadow.py, textsubline.py and run.py you can remove others to make it minimal.

**Comment by najisunade** [comment]
> After rewriting run.py by rename all variables to human-readable and restructure, I'm able to run it on Windows with GTX1070 with python command.
> The important file is 3 model .lib files, libsqla, libsqlb, libsqlc, shadow.py, textsubline.py and run.py you can remove others to make it minimal.

I try this step but i can't run please help.

**Comment by najisunade** [comment]
@comdet i already change every variebles to human-readable but i cant run because some package cant install, if you have know how please helpme.

**Comment by s1q** [comment]
> @comdet i already change every variables to human-readable
May I see your run.py file? I have problem with libsqla, libsqlb and libsqlc - i don`t know what this libraries do. Did you decompile it?

**Comment by najisunade** [comment]
@s1q libsqla it not library that file is libsqla.cp36-win_amd64.pyd but i dont know how to use them

**Comment by enextus** [comment]
Both files should be deleted:

libsqld.cp36-win_amd64.pyd
color.cp36-win_amd64.pyd

This file must be copied:

libsqld.py

This code must be inside:

def add(a, b, c):
	return a

**Comment by stacklikemind** [comment]
https://github.com/deepinstruction/deepnude_official
