### ISSUE TITLE
No module named libsqla

### ISSUE THREAD

**Issue by Montaxx** [open-deepnude/open-deepnude#7]
can't go past that error. any help?

**Comment by AlexHaber** [comment]
Use python 3.6

**Comment by 201521190031** [comment]
we have to run it in window os right?

**Comment by 201521190031** [comment]
No module named libsqld

**Comment by AlexHaber** [comment]
Use this https://raw.githubusercontent.com/diewland/open-deepnude/master/libsqld.py
Save to folder with libsqla, libsqlb and libsqlc files

**Comment by 201521190031** [comment]
thank you so much




------------------ 原始邮件 ------------------
发件人: "Alex Haber"<notifications@github.com>; 
发送时间: 2019年7月5日(星期五) 晚上9:47
收件人: "open-deepnude/open-deepnude"<open-deepnude@noreply.github.com>; 
抄送: "3137911713"<3137911713@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [open-deepnude/open-deepnude] No module named libsqla (#7)




Use this https://raw.githubusercontent.com/diewland/open-deepnude/master/libsqld.py
 Save to folder with libsqla, libsqlb and libsqlc files

**Comment by stacklikemind** [comment]
https://github.com/deepinstruction/deepnude_official

**Comment by xXmeme-machineXx** [comment]
You need to rename the pyds to `libmysqla.pyd`, `libmysqlb.pyd`, `libmysqlc.pyd` probably
